apiVersion: security.kubearmor.com/v1
kind: KubeArmorClusterPolicy
metadata:
  name: k8s-client-tool-exec
spec:
  action: Block
  message: Alert! k8s client tool executed inside container.
  process:
    matchPaths:
    - path: /usr/bin/crictl
    - path: /usr/bin/docker
    - path: /usr/bin/kubectl
    - path: /usr/local/bin/crictl
    - path: /usr/local/bin/docker
    - path: /usr/local/bin/kubectl
  selector:
    matchExpressions:
    - key: namespace
      operator: NotIn
      values:
      - kube-system
  severity: 5
  tags:
  - MITRE
  - MITRE_T1609_container_administration_command
  - MITRE_T1610_deploy_container
  - MITRE_TA0002_execution
  - NIST
  - NIST_800-53
  - NIST_800-53_AU-2
  - NIST_800-53_SI-4
